rootProject.name = "iota"
include("core")
include("base")
include("trigger-http")
include("trigger-shell")
include("handler-groovy")
include("handler-asyncjava")
include("loader-file")
include("examples")
include("trigger-dubbo-provider")
